# Generated by Django 5.2.8 on 2025-11-22 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poetry', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='category',
            field=models.CharField(choices=[('poem', 'Poem'), ('prose', 'Prose'), ('song', 'Song')], default='poem', max_length=10),
        ),
    ]
